# Generated by Django 4.2.21 on 2025-07-24 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0005_remove_bookproject_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('address_line', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='book.bookproject')),
            ],
        ),
    ]
