# Generated by Django 4.2.21 on 2025-07-24 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_shippingrequest_warehouse_delete_shippingaddress'),
        ('book', '0005_remove_bookproject_contact_phone'),
        ('book_shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProjectShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_info', to='book.bookproject')),
                ('shipping_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_project_info', to='shipping.shippingrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='BookShippingAddress',
        ),
    ]
