# Generated by Django 4.2.21 on 2025-07-25 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_bookproject_contact_phone'),
        ('book_shipping', '0002_bookprojectshipping_delete_bookshippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.JSONField()),
                ('shipping_rate', models.FloatField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='book.bookproject')),
            ],
        ),
        migrations.DeleteModel(
            name='BookProjectShipping',
        ),
    ]
