# Generated by Django 4.2.21 on 2025-07-25 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_bookproject_contact_phone'),
        ('book_shipping', '0003_shippingrequest_delete_bookprojectshipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Warehouse', max_length=255)),
                ('country_alpha2', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('address_line', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shippingrequest',
            name='book_project',
        ),
        migrations.CreateModel(
            name='BookShippingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_shipping_order', to='book.bookproject')),
                ('shipping_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_order', to='book_shipping.shippingrequest')),
            ],
            options={
                'verbose_name': 'Book Shipping Order',
                'verbose_name_plural': 'Book Shipping Orders',
            },
        ),
    ]
