# Generated by Django 4.2.21 on 2025-07-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0002_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_enabled', models.BooleanField(default=True, help_text='Enable/Disable Credit Card payments via Stripe')),
                ('paypal_enabled', models.BooleanField(default=True, help_text='Enable/Disable PayPal payments')),
                ('stripe_description', models.CharField(blank=True, default='Pay securely with your credit or debit card', max_length=255)),
                ('paypal_description', models.CharField(blank=True, default='Pay with your PayPal account', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
    ]
