# Generated by Django 4.2.21 on 2025-08-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentSettings',
        ),
    ]
