# Generated by Django 4.2.21 on 2025-08-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0004_delete_paymentsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_enabled', models.BooleanField(default=True)),
                ('paypal_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Method Settings',
            },
        ),
    ]
