# Generated by Django 4.2.21 on 2025-06-27 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comicbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicBindingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_pages', models.IntegerField(default=1)),
                ('max_pages', models.IntegerField(blank=True, default=9999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComicCoverFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='InteriorColor',
            new_name='ComicInteriorColor',
        ),
        migrations.RenameModel(
            old_name='PaperType',
            new_name='ComicPaperType',
        ),
        migrations.RemoveField(
            model_name='bindingtype',
            name='trim_size',
        ),
        migrations.DeleteModel(
            name='CoverFinish',
        ),
        migrations.RenameModel(
            old_name='TrimSize',
            new_name='ComicTrimSize',
        ),
        migrations.DeleteModel(
            name='BindingType',
        ),
        migrations.AddField(
            model_name='comicbindingtype',
            name='trim_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicbook.comictrimsize'),
        ),
    ]
