# Generated by Django 4.2.21 on 2025-07-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookproject_binding_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproject',
            name='cover_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
