# Generated by Django 4.2.23 on 2025-07-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_bookproject_cover_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproject',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
