# Generated by Django 4.2.23 on 2025-07-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookproject_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookproject',
            name='contact_phone',
        ),
    ]
