# Generated by Django 4.1 on 2025-10-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_widen_money_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproject',
            name='order_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid')], default='draft', help_text='Order status: draft (unpaid/incomplete) or paid (completed)', max_length=20),
        ),
    ]
