# Generated by Django 4.2.21 on 2025-07-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_shippingaddress_remove_shippingrate_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='apt_floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
